version: "3.9"

services:
  lab-service:
    build: .
    container_name: lab_service
    ports:
      - "8090:8090"
    volumes:
      - ./data:/app/data  # Где будет храниться база lab_results.db
    environment:
      - DATABASE_URL=sqlite:///./data/lab_results.db
      - APP_PORT=8000
    restart: always
